client all_clients {
    ipaddr = 0.0.0.0/0
    secret = $ENV{RADIUS_SECRET}
    require_message_authenticator = no
    nas_type = other
}

client localhost {
    ipaddr = 127.0.0.1
    secret = $ENV{RADIUS_SECRET}
    require_message_authenticator = no
    nas_type = other
}

client localhost_ipv6 {
    ipv6addr = ::1
    secret = $ENV{RADIUS_SECRET}
    require_message_authenticator = no
    nas_type = other
}
